function getCompassList() {
  return [{
    type: 1,
    id: 0,
    name: '美食推荐，我要去吃啥？',
    title: '美食',
    title_key: '美食',
    items: null
  }, {
    type: 1,
    id: 1,
    name: '游玩景点，周末去哪玩？',
    title: '景点',
    title_key: '旅游景点',
    items: null
  }, {
    type: 1,
    id: 2,
    name: '购物商场，去哪里逛街？',
    title: '购物',
    title_key: '综合商场',
    items: null
  }, {
    type: 1,
    id: 3,
    name: '休闲娱乐，去哪放松一下？',
    title: '休闲',
    title_key: '娱乐休闲',
    items: null
  }, {
    type: 0,
    id: 4,
    name: '石头剪刀布',
    title: '猜拳',
    items: [{
      name: '石头',
    }, {
      name: '剪刀',
    }, {
      name: '布',
    }]
  }, {
    type: 0,
    id: 5,
    name: '抛硬币',
    title: '决定',
    items: [{
      name: '正面',
    }, {
      name: '反面',
    }]
  }, {
    type: 2,
    id: 6,
    name: '真心话&大冒险',
    title: '游戏',
    items: [{
      problemType: 0,
      name: '真心话',
    }, {
      problemType: 1,
      name: '大冒险',
    }, {
      problemType: 2,
      name: 'PASS',
    }]
  }, {
    type: 10001,
    id: 7,
    name: '真心话题库',
    title: '游戏',
    problemType: 0,
  }, {
    type: 10001,
    id: 8,
    name: '大冒险题库',
    title: '游戏',
    problemType: 1,
  }, {
    type: 3,
    id: 9,
    name: '看哪部经典电影？',
    title: '电影',
    items: null
  }, {
    type: 0,
    id: 10,
    name: '周末怎么过？',
    title: '决定',
    items: [{
      name: '当然是逛吃逛吃',
    }, {
      name: '压力辣么大 玩会游戏吧',
    }, {
      name: '宅在家里吃泡面刷剧',
    }, {
      name: '什么周末？当我醒来就是周一',
    }, {
      name: '大风越狠我越要出去浪',
    }, {
      name: '组织朋友聚会',
    }, {
      name: '去电影院连刷三部电影',
    }, {
      name: '去公司加班/教室自习',
    }, {
      name: '出门扶老奶奶过马路',
    }, {
      name: '来一场说走就走的周边游',
    }]
  }, {
    type: 0,
    id: 11,
    name: '要不要辞职',
    title: '决定',
    items: [{
      name: '别瞎想 专心搬砖',
    }, {
      name: '我家有矿 想走就走',
    }, {
      name: '先找好下家再走',
    }, {
      name: '辞职 大爷不干了',
    }, {
      name: '明天再决定',
    }, {
      name: '请两天假放松一下',
    }, {
      name: '先冷静冷静再说',
    }, {
      name: '拿完年终奖再辞职',
    }, {
      name: '先努力学习提高能力',
    }, {
      name: '要想富 得创业',
    }, {
      name: '涨薪 不涨就辞职',
    }, {
      name: '忍无可忍 再忍一次',
    }]
  }, {
    type: 0,
    id: 12,
    name: '要不要表白',
    title: '决定',
    items: [{
      name: '表白',
    }, {
      name: '不表白',
    }, {
      name: '再等等',
    }, {
      name: '暗示一下',
    }]
  }, {
    type: 0,
    id: 13,
    name: '谁去取快递/外卖/跑腿',
    title: '决定',
    items: [{
      name: '最瘦的',
    }, {
      name: '微信好友最多的',
    }, {
      name: '个子最高的',
    }, {
      name: '离门口最近的',
    }, {
      name: '长得最好看的',
    }, {
      name: '年龄最小的',
    }, {
      name: '微信步数最少的',
    }, {
      name: '单身最久的',
    }, {
      name: '穿的最多的',
    }, {
      name: '头发最长的',
    }, {
      name: '手机电量最少的',
    }, {
      name: '双腿最直的',
    }]
  }, {
    type: 0,
    id: 14,
    name: '谁买单？',
    title: '决定',
    items: [{
      name: '身高最高的',
    }, {
      name: '微信好友最多的',
    }, {
      name: '最瘦的',
    }, {
      name: '身高第二高的',
    }, {
      name: '第二瘦的',
    }, {
      name: '年龄最小的',
    }, {
      name: '年龄最大的',
    }, {
      name: '微信好友第二多的',
    }, {
      name: '年龄第二大的',
    }, {
      name: '头发最长的',
    }, {
      name: '头发最短的',
    }, {
      name: '年龄第二小的',
    }]
  }, {
    type: 0,
    id: 15,
    name: '随机做泥',
    title: '决定',
    items: [{
      name: '水晶泥',
    }, {
      name: '网格泥',
    }, {
      name: '泡沫球泥',
    }, {
      name: '千丝泥',
    }, {
      name: '牛头泥',
    }, {
      name: '抹布泥',
    }, {
      name: '棉花泥',
    }, {
      name: '冰山泥',
    }, {
      name: '珠光泥',
    }, {
      name: '果冻泥',
    }, {
      name: '果酱泥',
    }, {
      name: '馒头泥',
    }, {
      name: '充气冰山泥',
    }, {
      name: '云朵泥',
    }, {
      name: '屁股泥',
    }, {
      name: '米粒泥',
    }, {
      name: '假水泥',
    }, {
      name: '史莱姆',
    }]
  }, {
    type: 0,
    id: 16,
    name: '做泥材料',
    title: '决定',
    items: [{
      name: '白色泡沫球',
    }, {
      name: '白胶',
    }, {
      name: '液体胶',
    }, {
      name: '珠光粉',
    }, {
      name: '闪粉亮片',
    }, {
      name: '银箔纸',
    }, {
      name: '甘油',
    }, {
      name: '剃须泡',
    }, {
      name: '12色亮片',
    }, {
      name: '48色闪粉',
    }, {
      name: '粘土',
    }, {
      name: '瓜尔胶粉',
    }, {
      name: '卸妆水',
    }, {
      name: '蹦砂水',
    }, {
      name: '马卡龙',
    }, {
      name: '色素',
    }]
  }]
};

module.exports = {
  getCompassList: getCompassList
}